# Generated by Django 3.1 on 2020-08-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
