# Generated by Django 3.1 on 2020-08-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_studentfilledstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentFilledStatus',
        ),
    ]
